platform :ios, '7.0'

# Yep.
inhibit_all_warnings!

# Core
pod 'AFNetworking'
pod 'Mantle', '~> 1.5.1'
pod 'ReactiveCocoa'
pod 'FLKAutoLayout', '~> 0.2.1'
pod 'REMenu', '~> 1.10'

# Language sugar
pod 'libextobjc', '~> 0.4.1'

# Stubs
pod 'OHHTTPStubs'

# Network
pod 'Overcoat', '~>2.0'
pod 'Overcoat/ReactiveCocoa', '~>2.0'
